name: Renovate
on:
  push:
    branches:
      - main
        #  schedule:
# The "*" (#42, asterisk) character has special semantics in YAML, so this
# string has to be quoted.
#    - cron: '0/30 * * * *'
env:
  LOG_LEVEL: debug
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Renovate
        uses: renovatebot/github-action@v24.119.4
        with:
          configurationFile: dist/src/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
