name: Renovate
on:
  push:
    branches:
      - main
        #  schedule:
# The "*" (#42, asterisk) character has special semantics in YAML, so this
# string has to be quoted.
#    - cron: '0/30 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: debug
        run: cat /etc/group
      - name: debug 2
        run: ls -lah /var/run/docker.sock
#       - name: Self-hosted Renovate
#         uses: renovatebot/github-action@v25.25.2
#         with:
#           configurationFile: dist/src/renovate-config.js
#           token: ${{ secrets.RENOVATE_TOKEN }}
      - name: Renovate
        uses: docker://renovate/renovate:25
        with:
          entrypoint: /bin/ls -al /var/run/docker.sock

        env:
          LOG_LEVEL: debug
          RENOVATE_CONFIG_FILE: dist/src/renovate-config.js
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_CONFIG: '{"token": "${{secrets.RENOVATE_TOKEN}}", "extends": ["github>hisabimbola/renovate-base"]}'
